apiVersion: apps/v1
kind: Deployment
metadata:
  name: voteapi-deployment
  labels:
    app: voteapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: voteapi
  template:
    metadata:
      labels:
        app: voteapi
    spec:
      containers:
        - name: voteapi
          image: macdoogles/voteservice:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: voteapi-configmap
                  key: allowed_origins
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: voteapi-configmap
                  key: mongodb_database
            - name: MONGO_CONN_STR
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-conn-str

---
apiVersion: v1
kind: Service
metadata:
  name: voteapi-service
spec:
  selector:
    app: voteapi
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voteapi-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
    - hosts:
        - apis.agaber.dev
      secretName: voteapi-tls-secret
  rules:
    - host: apis.agaber.dev
      http:
        paths:
          - path: /vote/api/.*
            pathType: Prefix
            backend:
              service:
                name: voteapi-service
                port:
                  number: 80
