# The values here must be base64 encoded.
# $ echo -n "password" | base64

# Or set this from the command line:
# $ kubectl create secret generic mysecret --from-literal="password=mernk8s"

apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-conn-str: bW9uZ29kYitzcnY6Ly9iYXh0ZXJmcmVlbHk6QlZtR3RmVDRhaG1WUnJoWkB1cy1jZW50cmFsLWdjcC1jbHVzdGVyLnlpbHFoazQubW9uZ29kYi5uZXQ=
