apiVersion: apps/v1
kind: Deployment
metadata:
  name: voteapi-deployment
  labels:
    app: voteapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: voteapi
  template:
    metadata:
      labels:
        app: voteapi
    spec:
      containers:
      - name: voteapi
        image: macdoogles/voteservice
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: voteapi-service
spec:
  selector:
    app: voteapi
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voteapi-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: agaber.dev
    http:
      paths:
      - path: /api/.*
        pathType: Prefix
        backend:
          service:
            name: voteapi-service
            port: 
              number: 80