apiVersion: apps/v1
kind: Deployment
metadata:
  name: voteui-deployment
  labels:
    app: voteui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: voteui
  template:
    metadata:
      labels:
        app: voteui
    spec:
      containers:
        - name: voteui
          image: macdoogles/voteui
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: voteui-service
spec:
  selector:
    app: voteui
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voteui-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - agaber.dev
      secretName: voteapi-tls-secret
  rules:
    - host: agaber.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: voteui-service
                port:
                  number: 80
